#!/usr/bin/env bash
# Customizing a 404-error_page

# Updating Packages before performing installations
apt-get update
apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Creating an HTTP response header
sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configurations for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
 service nginx restart


